In [76]:
import numpy as np
import pandas as pd

In [77]:
data = pd.read_csv("pcadata.csv")
data.tail()

Unnamed: 0  WORD_FREQ_MAKE  WORD_FREQ_ADDRESS  WORD_FREQ_ALL  \
4205        4205        0.685518          -0.248027       0.637104   
4206        4206       -0.347922          -0.248027      -0.565245   
4207        4207        0.652181          -0.248027       0.016537   
4208        4208        2.852406          -0.248027      -0.565245   
4209        4209       -0.347922          -0.248027       0.695282   

      WORD_FREQ_3D  WORD_FREQ_OUR  WORD_FREQ_OVER  WORD_FREQ_REMOVE  \
4205     -0.046644      -0.473040        0.772994         -0.295731   
4206     -0.046644      -0.473040       -0.350205         -0.295731   
4207     -0.046644      -0.473040       -0.350205         -0.295731   
4208     -0.046644      -0.007737       -0.350205         -0.295731   
4209     -0.046644      -0.473040       -0.350205         -0.295731   

      WORD_FREQ_INTERNET  WORD_FREQ_ORDER  ...  CHAR_FREQ_;  CHAR_FREQ_(  \
4205           -0.263265        -0.325617  ...    -0.160010     0.320730   
4206           -0.263265        -0.325617  ...    -0.160010    -0.525294   
4207           -0.263265        -0.325617  ...     0.243945     2.093004   
4208           -0.263265        -0.325617  ...    -0.160010    -0.317435   
4209           -0.263265        -0.325617  ...    -0.160010    -0.525294   

      CHAR_FREQ_[  CHAR_FREQ_!  CHAR_FREQ_$  CHAR_FREQ_#  \
4205    -0.164364    -0.333407    -0.317325    -0.105071   
4206    -0.164364     0.085226    -0.317325    -0.105071   
4207    -0.164364    -0.333407    -0.317325    -0.105071   
4208    -0.164364    -0.333407    -0.317325    -0.105071   
4209    -0.164364    -0.185166    -0.317325    -0.105071   

      CAPITAL_RUN_LENGTH_AVERAGE  CAPITAL_RUN_LENGTH_LONGEST  \
4205                   -0.127986                   -0.246243   
4206                   -0.115525                   -0.241232   
4207                   -0.120081                   -0.231210   
4208                   -0.127835                   -0.236221   
4209                   -0.124727                   -0.236221   

      CAPITAL_RUN_LENGTH_TOTAL  SPAM  
4205                 -0.328464     0  
4206                 -0.448093     0  
4207                 -0.279966     0  
4208                 -0.344630     0  
4209                 -0.406061     0  

[5 rows x 59 columns]

In [78]:
data.shape

(4210, 59)

In [79]:
data["SPAM"].value_counts()

0    2531
1    1679
Name: SPAM, dtype: int64

In [80]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4210 entries, 0 to 4209
Data columns (total 59 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Unnamed: 0                  4210 non-null   int64  
 1   WORD_FREQ_MAKE              4210 non-null   float64
 2   WORD_FREQ_ADDRESS           4210 non-null   float64
 3   WORD_FREQ_ALL               4210 non-null   float64
 4   WORD_FREQ_3D                4210 non-null   float64
 5   WORD_FREQ_OUR               4210 non-null   float64
 6   WORD_FREQ_OVER              4210 non-null   float64
 7   WORD_FREQ_REMOVE            4210 non-null   float64
 8   WORD_FREQ_INTERNET          4210 non-null   float64
 9   WORD_FREQ_ORDER             4210 non-null   float64
 10  WORD_FREQ_MAIL              4210 non-null   float64
 11  WORD_FREQ_RECEIVE           4210 non-null   float64
 12  WORD_FREQ_WILL              4210 non-null   float64
 13  WORD_FREQ_PEOPLE            4210 

In [81]:
data.describe()

Unnamed: 0  WORD_FREQ_MAKE  WORD_FREQ_ADDRESS  WORD_FREQ_ALL  \
count  4210.000000    4.210000e+03       4.210000e+03   4.210000e+03   
mean   2104.500000   -2.698337e-07       3.741093e-07  -2.019002e-08   
std    1215.466646    1.000119e+00       1.000119e+00   1.000119e+00   
min       0.000000   -3.479220e-01      -2.480270e-01  -5.652450e-01   
25%    1052.250000   -3.479220e-01      -2.480270e-01  -5.652450e-01   
50%    2104.500000   -3.479220e-01      -2.480270e-01  -5.652450e-01   
75%    3156.750000   -3.479220e-01      -2.480270e-01   2.880350e-01   
max    4209.000000    1.478696e+01       3.119145e+01   9.325045e+00   

       WORD_FREQ_3D  WORD_FREQ_OUR  WORD_FREQ_OVER  WORD_FREQ_REMOVE  \
count  4.210000e+03   4.210000e+03    4.210000e+03      4.210000e+03   
mean   3.536817e-07  -5.605701e-08   -3.327791e-07     -1.705463e-07   
std    1.000119e+00   1.000119e+00    1.000119e+00      1.000119e+00   
min   -4.664400e-02  -4.730400e-01   -3.502050e-01     -2.957310e-01   
25%   -4.664400e-02  -4.730400e-01   -3.502050e-01     -2.957310e-01   
50%   -4.664400e-02  -4.730400e-01   -3.502050e-01     -2.957310e-01   
75%   -4.664400e-02   1.231300e-01   -3.502050e-01     -2.957310e-01   
max    3.160992e+01   1.406769e+01    2.095434e+01      1.800571e+01   

       WORD_FREQ_INTERNET  WORD_FREQ_ORDER  ...   CHAR_FREQ_;   CHAR_FREQ_(  \
count        4.210000e+03     4.210000e+03  ...  4.210000e+03  4.210000e+03   
mean        -3.403800e-07    -1.337292e-07  ...  3.413302e-07  7.363420e-08   
std          1.000119e+00     1.000119e+00  ...  1.000119e+00  1.000119e+00   
min         -2.632650e-01    -3.256170e-01  ... -1.600100e-01 -5.252940e-01   
25%         -2.632650e-01    -3.256170e-01  ... -1.600100e-01 -5.252940e-01   
50%         -2.632650e-01    -3.256170e-01  ... -1.600100e-01 -2.590880e-01   
75%         -2.632650e-01    -3.256170e-01  ... -1.600100e-01  1.821570e-01   
max          2.681886e+01     1.831957e+01  ...  1.720613e+01  3.503689e+01   

        CHAR_FREQ_[   CHAR_FREQ_!   CHAR_FREQ_$   CHAR_FREQ_#  \
count  4.210000e+03  4.210000e+03  4.210000e+03  4.210000e+03   
mean   7.980998e-08 -1.218527e-07  2.353919e-07  6.840855e-08   
std    1.000119e+00  1.000119e+00  1.000119e+00  1.000119e+00   
min   -1.643640e-01 -3.334070e-01 -3.173250e-01 -1.050710e-01   
25%   -1.643640e-01 -3.334070e-01 -3.173250e-01 -1.050710e-01   
50%   -1.643640e-01 -3.144320e-01 -3.173250e-01 -1.050710e-01   
75%   -1.643640e-01  5.913600e-02 -9.619700e-02 -1.050710e-01   
max    3.843832e+01  3.818318e+01  2.472857e+01  4.538756e+01   

       CAPITAL_RUN_LENGTH_AVERAGE  CAPITAL_RUN_LENGTH_LONGEST  \
count                4.210000e+03                4.210000e+03   
mean                 2.612827e-08               -2.161520e-08   
std                  1.000119e+00                1.000119e+00   
min                 -1.322700e-01               -2.562650e-01   
25%                 -1.133378e-01               -2.261990e-01   
50%                 -9.313800e-02               -1.861100e-01   
75%                 -5.060250e-02               -4.079000e-02   
max                  3.310208e+01                4.979423e+01   

       CAPITAL_RUN_LENGTH_TOTAL         SPAM  
count              4.210000e+03  4210.000000  
mean              -1.662708e-09     0.398812  
std                1.000119e+00     0.489712  
min               -4.691090e-01     0.000000  
25%               -4.060610e-01     0.000000  
50%               -3.066405e-01     0.000000  
75%               -2.818025e-02     1.000000  
max                2.513787e+01     1.000000  

[8 rows x 59 columns]

In [82]:
data.head()

Unnamed: 0  WORD_FREQ_MAKE  WORD_FREQ_ADDRESS  WORD_FREQ_ALL  WORD_FREQ_3D  \
0           0       -0.347922           1.161025       0.675889     -0.046644   
1           1        0.352150           0.368433       0.404391     -0.046644   
2           2       -0.147901          -0.248027       0.811639     -0.046644   
3           3       -0.347922          -0.248027      -0.565245     -0.046644   
4           4       -0.347922          -0.248027      -0.565245     -0.046644   

   WORD_FREQ_OUR  WORD_FREQ_OVER  WORD_FREQ_REMOVE  WORD_FREQ_INTERNET  \
0      -0.007737       -0.350205         -0.295731           -0.263265   
1      -0.269470        0.664297          0.232922           -0.092630   
2       1.315470        0.338207          0.182574            0.029252   
3       0.443026       -0.350205          0.484661            1.272445   
4       0.443026       -0.350205          0.484661            1.272445   

   WORD_FREQ_ORDER  ...  CHAR_FREQ_;  CHAR_FREQ_(  CHAR_FREQ_[  CHAR_FREQ_!  \
0        -0.325617  ...    -0.160010    -0.525294    -0.164364     0.589246   
1        -0.325617  ...    -0.160010    -0.043936    -0.164364     0.107759   
2         1.943000  ...    -0.120407    -0.003822    -0.164364    -0.006090   
3         0.773244  ...    -0.160010    -0.025702    -0.164364    -0.170935   
4         0.773244  ...    -0.160010    -0.032996    -0.164364    -0.173306   

   CHAR_FREQ_$  CHAR_FREQ_#  CAPITAL_RUN_LENGTH_AVERAGE  \
0    -0.317325    -0.105071                   -0.049117   
1     0.433676     0.005053                   -0.008143   
2     0.450365    -0.082129                    0.133876   
3    -0.317325    -0.105071                   -0.055724   
4    -0.317325    -0.105071                   -0.055724   

   CAPITAL_RUN_LENGTH_LONGEST  CAPITAL_RUN_LENGTH_TOTAL  SPAM  
0                    0.044398                 -0.021310     1  
1                    0.244841                  1.191142     1  
2                    2.169089                  3.181179     1  
3                   -0.060834                 -0.161954     1  
4                   -0.060834                 -0.161954     1  

[5 rows x 59 columns]

In [83]:
x = data.iloc[:,0:57]
x.head()

Unnamed: 0  WORD_FREQ_MAKE  WORD_FREQ_ADDRESS  WORD_FREQ_ALL  WORD_FREQ_3D  \
0           0       -0.347922           1.161025       0.675889     -0.046644   
1           1        0.352150           0.368433       0.404391     -0.046644   
2           2       -0.147901          -0.248027       0.811639     -0.046644   
3           3       -0.347922          -0.248027      -0.565245     -0.046644   
4           4       -0.347922          -0.248027      -0.565245     -0.046644   

   WORD_FREQ_OUR  WORD_FREQ_OVER  WORD_FREQ_REMOVE  WORD_FREQ_INTERNET  \
0      -0.007737       -0.350205         -0.295731           -0.263265   
1      -0.269470        0.664297          0.232922           -0.092630   
2       1.315470        0.338207          0.182574            0.029252   
3       0.443026       -0.350205          0.484661            1.272445   
4       0.443026       -0.350205          0.484661            1.272445   

   WORD_FREQ_ORDER  ...  WORD_FREQ_TABLE  WORD_FREQ_CONFERENCE  CHAR_FREQ_;  \
0        -0.325617  ...        -0.073094             -0.116407    -0.160010   
1        -0.325617  ...        -0.073094             -0.116407    -0.160010   
2         1.943000  ...        -0.073094             -0.116407    -0.120407   
3         0.773244  ...        -0.073094             -0.116407    -0.160010   
4         0.773244  ...        -0.073094             -0.116407    -0.160010   

   CHAR_FREQ_(  CHAR_FREQ_[  CHAR_FREQ_!  CHAR_FREQ_$  CHAR_FREQ_#  \
0    -0.525294    -0.164364     0.589246    -0.317325    -0.105071   
1    -0.043936    -0.164364     0.107759     0.433676     0.005053   
2    -0.003822    -0.164364    -0.006090     0.450365    -0.082129   
3    -0.025702    -0.164364    -0.170935    -0.317325    -0.105071   
4    -0.032996    -0.164364    -0.173306    -0.317325    -0.105071   

   CAPITAL_RUN_LENGTH_AVERAGE  CAPITAL_RUN_LENGTH_LONGEST  
0                   -0.049117                    0.044398  
1                   -0.008143                    0.244841  
2                    0.133876                    2.169089  
3                   -0.055724                   -0.060834  
4                   -0.055724                   -0.060834  

[5 rows x 57 columns]

In [84]:
y = data.iloc[:,-1]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: SPAM, dtype: int64

In [85]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [86]:
x = scaler.fit_transform(x)
x[0:5]

array([[-1.73163944e+00, -3.47921694e-01,  1.16102473e+00,
         6.75889009e-01, -4.66443548e-02, -7.73694379e-03,
        -3.50204627e-01, -2.95730813e-01, -2.63264636e-01,
        -3.25616851e-01, -3.78366309e-01, -3.07836420e-01,
         8.47631264e-02, -3.15758927e-01, -1.76898987e-01,
        -1.85015569e-01,  8.29790727e-02, -3.25938850e-01,
         2.03531292e+00,  1.19664108e-01, -1.68067636e-01,
         1.30489119e-01, -1.22848356e-01, -2.86432866e-01,
        -2.10737045e-01, -3.42409901e-01, -3.08500363e-01,
        -2.08345727e-01, -2.40162603e-01, -1.70587229e-01,
        -2.36121176e-01, -1.64102339e-01, -1.49368148e-01,
        -1.79821647e-01, -1.51690935e-01, -2.03472801e-01,
        -2.57147815e-01, -3.38036553e-01, -6.15660341e-02,
        -1.87653192e-01, -1.91804015e-01, -1.30233188e-01,
        -1.78329236e-01, -2.10365694e-01, -1.31986844e-01,
        -3.06106866e-01, -2.04024811e-01, -7.30943168e-02,
        -1.16407083e-01, -1.60010349e-01, -5.25294094e-0

In [87]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [88]:
x_train.shape

(3368, 57)

In [89]:
x_test.shape

(842, 57)

In [90]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [91]:
pred = model.predict(x_test)
pred[0:5]

array([0, 0, 1, 1, 0], dtype=int64)

In [92]:
y_test[0:5]

3134    0
2500    0
776     1
11      1
3505    0
Name: SPAM, dtype: int64

In [93]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,pred)
accuracy

0.9584323040380047

In [94]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,pred)
cm

array([[485,  20],
       [ 15, 322]], dtype=int64)

In [95]:
results = pd.DataFrame(data=[y_test.values],index=["y_test","pred"])
results.transpose()

y_test  pred
0         0     0
1         0     0
2         1     1
3         1     1
4         0     0
..      ...   ...
837       0     0
838       1     1
839       0     0
840       1     1
841       0     0

[842 rows x 2 columns]

In [96]:
correct_sum = []
for i in range(1,30):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train,y_train)
    pred = model.predict(x_test)
    correct = np.sum(pred==y_test)
    correct_sum.append(correct)

In [97]:
correct_sum

[807,
 791,
 808,
 802,
 807,
 807,
 805,
 803,
 806,
 807,
 813,
 809,
 805,
 804,
 805,
 803,
 802,
 801,
 800,
 803,
 803,
 805,
 802,
 803,
 804,
 801,
 801,
 802,
 802]

In [98]:
results = pd.DataFrame(data=correct_sum)
results.index = results.index+1
results.T

1    2    3    4    5    6    7    8    9    10  ...   20   21   22   23  \
0  807  791  808  802  807  807  805  803  806  807  ...  803  803  805  802   

    24   25   26   27   28   29  
0  803  804  801  801  802  802  

[1 rows x 29 columns]

In [99]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(x_train,y_train)
pred = model.predict(x_test)

In [100]:
accuracy_score(y_test,pred)

0.9584323040380047